version: '3.5'

services:
  db:
    container_name: db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Asdfqwer1234"
      ACCEPT_EULA: "Y"
    volumes:
      - "/data/Roulette/:/var/lib/mssql"
