version: '3.4'

services:

  db:
    container_name: db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Asdfqwer1234"
      ACCEPT_EULA: "Y"
    volumes:
      - "/data/roulette/:/var/lib/mssql"
    networks:
      - roulette.api

  roulette.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - SQLSERVER_HOST=db

    build:
      context: .
      dockerfile: Roulette.Api/Dockerfile

    image: ${DOCKER_REGISTRY-}roulette

    restart: on-failure

    networks:
      - roulette.api
    ports:
      - "8000:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - "db"
    links:
      - "db"

networks:
  roulette.api:
   name: roulette.api
